export default function Skills() {
  return (
    <div id="skills">SkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkillsSkills</div>
  )
}